# Generated by Django 4.1.2 on 2022-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_des',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
