# Generated by Django 4.1.2 on 2022-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
