# Generated by Django 4.1.2 on 2022-11-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='number',
            new_name='phone',
        ),
    ]
