# Generated by Django 4.1.2 on 2022-11-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
    ]
