# Generated by Django 4.1.2 on 2022-11-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_title_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Status', upload_to='shop/images'),
        ),
    ]
