# Generated by Django 4.1.2 on 2022-11-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery',
        ),
    ]
